
spring:
  datasource:
    url: jdbc:h2:mem:workshop
    #url: jdbc:h2:file:~/workshop.db;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      show_sql: true
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
server:
  port: ${PORT:8080}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

security:
  jwt:
    token:
      secret-key: nSU1A70Dk3AlJbw69LyKDtFLWhcAEVMsBeFmDDjDjzkBCbQWcKEa86BudY56IrWyYAegPAZNwNislqlrTdxiuw==
      expire-length: 1800 # seconds
      issuer: workshop-spring-boot

# JSONDoc configuration
jsondoc:
  version: 1.0
  basePath: http://localhost:8080
  packages:
    - org.desarrolladorslp.workshops.springboot
